# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
java_version=25
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT
modmenu_version=18.0.0-alpha.6
fabric_api_version=0.144.0+26.1

# Mod Properties
mod_version = fabric-1.1.1+mc26.1
maven_group = com.diamondgoobird
archives_base_name = trial-spawner-timer